# Generated by Django 5.2.8 on 2025-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
