# Generated by Django 5.2.9 on 2025-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_comment_like_delete_article_newsarticle_likes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('urlToImage', models.CharField(blank=True, max_length=500, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
    ]
